{{- if .Values.varnish.enabled -}}
apiVersion: v1
kind: Domain
metadata:
  name: varnish
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-varnish
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Domain }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "name" . }}-varnish
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
