# Read the documentation: 
# https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
# https://symfonycasts.com/screencast/symfony-uploads/flysystem
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
        public_uploads_image_product_adapter:
            local:
                #directory: '%kernel.project_dir%/public/assets/uploads/img/product'
                directory: '%kernel.project_dir%/public/%env(UPLOAD_SUPPLIER_PRODUCT_IMAGE_DIRECTORY)%'
        public_uploads_image_category_adapter:
            local:
                #directory: '%kernel.project_dir%/public/assets/uploads/img/category'
                directory: '%kernel.project_dir%/public/%env(UPLOAD_CATEGORY_IMAGE_DIRECTORY)%'
        private_uploads_image_customer_adapter:
            local:
                #directory: '%kernel.project_dir%/web/uploads/img/profile/customer'
                directory: '%kernel.project_dir%/%env(UPLOAD_CUSTOMER_IMAGE_DIRECTORY)%'
        private_uploads_image_supplier_adapter:
            local:
                #directory: '%kernel.project_dir%/web/uploads/img/profile/supplier'
                directory: '%kernel.project_dir%/%env(UPLOAD_SUPPLIER_IMAGE_DIRECTORY)%'
        private_uploads_image_admin_adapter:
            local:
                #directory: '%kernel.project_dir%/web/uploads/img/profile/admin'
                directory: '%kernel.project_dir%/%env(UPLOAD_ADMIN_IMAGE_DIRECTORY)%'
        private_downloads_bill_customer_adapter:
            local:
                directory: '%kernel.project_dir%/%env(DOWNLOAD_BILL_CUSTOMER_DIRECTORY)%'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            #alias: League\Flysystem\Filesystem
        public_image_product_filesystem:
            adapter: public_uploads_image_product_adapter
            alias: image_product.filesystem
        public_image_category_filesystem:
            adapter: public_uploads_image_category_adapter
            alias: image_category.filesystem
        private_image_customer_filesystem:
            adapter: private_uploads_image_customer_adapter
            alias: image_customer.filesystem
        private_image_supplier_filesystem:
            adapter: private_uploads_image_supplier_adapter
            alias: image_supplier.filesystem
        private_image_admin_filesystem:
            adapter: private_uploads_image_admin_adapter
            alias: image_admin.filesystem
        private_bill_customer_filesystem:
            adapter: private_downloads_bill_customer_adapter
            alias: bill_customer.filesystem
