swiftmailer:
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: gmail
    auth_mode: oauth
    port: 465
    encryption: tls
    #host: smtp.gmail.com
    host: localhost
    username: '%env(MAILER_USER)%'
    password: '%env(MAILER_USER_PASSWORD)%'
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
