twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        # Env variable used for invoice template
        # In dev-mode, when build the docker images this parameter MUST be commented
        # Uncomment this parameter after building the docker containers
        APP_OWNER_ADDRESS: '%env(resolve:APP_OWNER_ADDRESS)%'
        APP_OWNER_PHONE_NUMBER: '%env(resolve:APP_OWNER_PHONE_NUMBER)%'
        APP_OWNER_CONTACT_EMAIL: '%env(resolve:APP_OWNER_CONTACT_EMAIL)%'
        APP_HOST_URL: '%env(resolve:APP_HOST_URL)%'
        APP_FULLNAME: '%env(resolve:APP_FULLNAME)%'
