vich_uploader:
    db_driver: orm

    mappings:
        image_category:
            uri_prefix: /images/category/create
            upload_destination: '%kernel.project_dir%/public/assets/uploads/img/category'
        image_products:
            uri_prefix: /images/product/create
            upload_destination: '%kernel.project_dir%/public/assets/uploads/img/products'
        image_admin:
            uri_prefix: /images/admin/create
            upload_destination: '%kernel.project_dir%/public/assets/uploads/img/profil/admin'
        image_customer:
            uri_prefix: /images/customer/create
            upload_destination: '%kernel.project_dir%/public/assets/uploads/img/profil/customer'
        image_supplier:
            uri_prefix: /images/supplier/create
            upload_destination: '%kernel.project_dir%/public/assets/uploads/img/profil/supplier'
            inject_on_load: true
