App\Entity\Admin:
    shortName: 'Admin'
    description: 'Administrator of this platform'
    collectionOperations:
        get:
            method: 'GET'
            path: '/admins.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "has_role('ROLE_SUPER_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY', get)"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        # Attention: Api-platform est configuré pour intégrer les routes POST dans les opérations sur les collections
        post:
            method: 'POST'
            path: '/admin/create'
            requirements:
                admin: App\Entity\Admin
            access_control: "has_role('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY', post)"
            schemes: ['https']
            controller: App\Controller\Admin\CreateAdmin::class
    itemOperations:
        get:
            method: 'GET'
            path: '/admin/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "has_role('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY', get)"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        
        put:
            method: 'PUT'
            path: '/admin/{id}'
            requirements:
                id: '\d+'
            access_control: "has_role('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY', put)"
            schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/admin/{id}'
            requirements:
                id: '\d+'
            security: 'has_role("ROLE_ADMIN")'
            schemes: ['https']
