App\Entity\Bill:
    shortName: 'Bill'
    description: 'Invoice made for a payment on this platform'
    iri: 'https://schema.org/Invoice'
    collectionOperations:
        get:
            method: 'GET'
            path: '/bills.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
    itemOperations:
        get:
            method: 'GET'
            path: '/bill/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_ADMIN')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
