App\Entity\BillSupplier:
    shortName: 'BillSupplier'
    description: 'Bill made for a supplier:"s purchased by a customer'
    iri: 'https://schema.org/Invoice'
    collectionOperations:
        get:
            method: 'GET'
            path: '/supplier_bills.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "has_role('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
    itemOperations:
        get:
            method: 'GET'
            path: '/supplier_bill/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "is_granted('IS_AUTHENTICATED_FULLY')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        delete:
            method: 'DELETE'
            path: '/supplier_bill/{id}'
            requirements:
                id: '\d+'
            access_control: "is_granted('IS_AUTHENTICATED_FULLY') and has_role('ROLE_ADMIN')"
            schemes: ['https']
