App\Entity\Category:
    shortName: 'Category'
    description: 'Category of product sold on this platgorm'
    collectionOperations:
        get:
            method: 'GET'
            path: '/categories.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        # Opération POST à inclure dans les opérations sur les collections  
        getNames:
            method: 'GET'
            path: '/categories_names'
            schemes: ["https","http"]
            controller: App\Controller\Category\GetCategoriesNameAction
        post:
            method: 'POST'
            path: '/category/create'
            access_control: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            schemes: ['https']
            controller: App\Controller\Categry\CreateCategoryAction
    itemOperations:
        get:
            method: 'GET'
            path: '/category/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send        
        put:
            method: 'PUT'
            path: '/category/{id}'
            requirements:
                id: '\d+'
            access_control: 'is_granted("IS_AUTHENTICATED_REMEMBERED") and is_granted("ROLE_ADMIN")'
            schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/category/{id}'
            requirements:
                id: '\d+'
            access_control: 'is_granted("IS_AUTHENTICATED_REMEMBERED") and is_granted("ROLE_ADMIN")'
            schemes: ['https']    
    subresourceOperations:
        products_get_subresource:
            method: 'GET'
            path: '/category/{id}/products.{_format}'
            defaults:
                _format: 'jsonld'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
