App\Entity\Comment:
    shortName: 'Comment'
    description: 'Comment made by customers on the suppliers:" product bought '
    iri: 'https://schema.org/Comment'
    collectionOperations:
        get:
            method: 'GET'
            path: '/comments.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            security: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        getCommentsSupplierProduct:
            method: 'GET'
            path: '/comments/supplier_product/{id}'
            requirements: 
                id: '\d+'
            default: 
                _api_receive: false
            schemes: ['https']
            accessControl: "is_granted('ROLE_MEMBER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            controller: App\Action\Comment\GetCommentsSupplierProductAction
        post:
            method: 'POST'
            path: '/comment/create'
            defaults:
                _api_receive: false
            security: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            schemes: ['https']
            controller: App\Action\Comment\CreateCommentAction
    itemOperations:
        get:
            method: 'GET'
            path: '/comment/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send        
        put:
            method: 'PUT'
            path: '/comment/{id}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_CUSTOMER") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/comment/{id}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_CUSTOMER") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            schemes: ['https']
        
