App\Entity\Customer:
    shortName: 'Customer'
    description: 'Customer of this platform'
    iri: 'https://schema.org/Person'
    routePrefix: '/members'
    collectionOperations:
        get:
            method: 'GET'
            path: '/customers.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            security: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        post:
            method: 'POST'
            path: '/customer/create'
            security: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_FULLY')"
            schemes: ['https']
            controller: App\Action\Customer\CreateCustomer::class
    itemOperations:
        get:
            method: 'GET'
            path: '/customer/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            security: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_FULLY')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        
        put:
            method: 'PUT'
            path: '/customer/{id}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_CUSTOMER") and is_granted("IS_AUTHENTICATED_FULLY")'
            schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/customer/{id}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_ADMIN") and is_granted("IS_AUTHENTICATED_FULLY")'
            schemes: ['https']
    subresourceOperations:
        favorites_get_subresource:
            method: 'GET'
            path: '/customer/{id}/favorites.{_format}'
            defaults:
                _format: 'jsonld'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            security: 'is_granted("ROLE_CUSTOMER")'
            schemes: ['https']
        shopping_cards_get_subresource:
            method: 'GET'
            path: '/customer/{id}/shopping_cards.{_format}'
            defaults:
                _format: 'jsonld'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            security: 'is_granted("ROLE_CUSTOMER")'
            schemes: ['https']
        
