App\Entity\Favorite:
    shortName: 'Favorite'
    description: 'Product loved by a customer'
    collectionOperations:
        get:
            method: 'GET'
            path: '/favorites.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        getIds:
            method: 'GET'
            path: '/favorites/ids'
            requirements: 
                id: '\d+'
                _format: 'json\jsonld'
            defaults:
                _format: 'json'
            schemes: ['https']
            access_control: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_FULLY')"
            controller: App\Controller\Favorite\GetFavoriteIdsAction
        post:
            method: 'POST'
            path: '/favorite/create'
            defaults:
                _api_receive: false
            access_control: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            schemes: ['https']
            controller: App\Controller\Favorite\CreateFavoriteAction
    itemOperations:
        get:
            method: 'GET'
            path: '/favorite/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        delete:
            method: 'DELETE'
            path: '/favorite/{id}'
            requirements:
                id: '\d+'
            access_control: 'is_granted("ROLE_CUSTOMER") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            schemes: ['https']
            controller: App\Controller\Favorite\DeleteFavoriteAction
