App\Entity\Image:
    shortName: 'Image'
    description: 'Images illustrating products and person'
    iri: 'https://schema;org/ImageObject'
    collectionOperations:
        get:
            method: 'GET'
            path: '/images.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        post:
            method: 'POST'
            path: '/image/create'
            access_control: "is_granted('ROLE_MEMBER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            schemes: ['https']
            controller: App\Controller\Image\CreateImageAction::class
    itemOperations:
        get:
            method: 'GET'
            path: '/image/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send        
        #put:
        #    method: 'PUT'
        #    path: '/image/{id}'
        #    requirements:
        #        id: '\d+'
        #    access_control: 'is_granted("ROLE_MEMBER") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
        #    schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/image/{id}'
            requirements:
                id: '\d+'
            access_control: 'is_granted("ROLE_MEMBER") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            schemes: ['https']
