App\Entity\OrderSet:
    shortName: 'OrderSet'
    description: "Order's set for a purchase by a client on the platform"
    iri: 'https://schema.org/OrderAction'
    collectionOperations:
        get:
            method: 'GET'
            path: '/order_sets.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            security: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        my_orders:
            method: 'GET'
            path: '/my_orders'
            requirements:
                page: '\d+'
            defaults:
                _api_receive: false
            schemes: ['https']
            security: "(is_granted('ROLE_CUSTOMER') or is_granted('ROLE_SUPPLIER') ) and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            controller: App\Controller\OrderSet\GetCustomerOrdersAction
        post:
            method: 'POST'
            path: '/order_set/create'
            security: "is_granted('ROLE_MEMBER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            schemes: ['https']
            controller: App\Controller\OrderSet\CreateOrderSetAction
        getOrderSetSuccess:
            method: 'POST'
            path: '/order_set/success'
            requirements:
                sessionId: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            security: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
            controller: App\Controller\OrderSet\GetOrderSetSuccessAction
    itemOperations:
        get:
            method: 'GET'
            path: '/order_set/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            security: "is_granted('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send            
        put:
            method: 'PUT'
            path: '/order_set/{id}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_ADMIN") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/order_set/{id}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_ADMIN") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            schemes: ['https']
