App\Entity\Payment:
    shortName: 'Payment'
    description: 'Payment made on this platform'
    iri: 'https://schema.org/PayAction'
    collectionOperations:
        get:
            method: 'GET'
            path: '/payments.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "has_role('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        post:
            method: 'POST'
            path: '/payment/create'
            defaults:
                _api_receive: false
            access_control: "has_role('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_FULLY')"
            schemes: ['https']
            controller: App\Controller\Payment\CreatePaymentAction
    itemOperations:
        get:
            method: 'GET'
            path: '/payment/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "has_role('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_REMEMBERED')"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        
        delete:
            method: 'DELETE'
            path: '/payment/{id}'
            requirements:
                id: '\d+'
            access_control: 'has_role("ROLE_ADMIN") and is_granted("IS_AUTHENTICATED_FULLY")'
            schemes: ['https']
