App\Entity\Product:
    shortName: 'Product'
    description: 'Products sold on this platform'
    iri: 'https://schema.org/Product'
    attributes:
        pagination_items_per_page: 25
    collectionOperations:
        get:
            method: 'GET'
            path: '/products.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _format: 'jsonld'
            # host: 'localhost'
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send
        post:
            method: 'POST'
            path: '/product/create'
            requirements:
                product: App\Entity\Product
            access_control: "has_role('ROLE_SUPPLIER') and is_granted('IS_AUTHENTICATED_FULLY', post)"
            schemes: ['https']
            controller: App\Controller\Product\CreateProduct::class
    itemOperations:
        get:
            method: 'GET'
            path: '/product/{id}.{_format}'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
            defaults:
                _format: 'json'
            # host: 'localhost'
            schemes: ['https']
            access_control: "has_role('ROLE_CUSTOMER') and is_granted('IS_AUTHENTICATED_FULLY', get)"
            #options:
            #    my_option: 'my_option_value'
            status: 200 # customize the HTTP status code to send        
        put:
            method: 'PUT'
            path: '/product/{id}'
            requirements:
                id: '\d+'
            access_control: 'has_role("ROLE_SUPPLIER")'
            schemes: ['https']
        delete:
            method: 'DELETE'
            path: '/product/{id}'
            requirements:
                id: '\d+'
            security: 'has_role("ROLE_ADMIN")'
            schemes: ['https']
    subresourceOperations:
        images_get_subresource:
            method: 'GET'
            path: '/product/{id}/images.{_format}'
            defaults:
                _format: 'jsonld'
            requirements:
                id: '\d+'
                _format: 'json\jsonld\html'
        
