App\Entity\UserTemp:
    shortName: 'UserTemp'
    description: "Subscriber to this platform"
    iri: 'https://schema.org/Person'
    collectionOperations:
        get:
            method: 'GET'
            path: '/registers.{_format}'
            requirements: 
                _formats: 'json\jsonld\html'
            defaults:
                _format: 'json'
            schemes: ['https']
            security: "is_granted('ROLE_ADMIN') and is_granted('IS_AUTHENTICATED_FULLY')"
        # La méthode POST doit être enregistré dans les actions sur les opérations    
        post:
            method: 'POST'
            path: '/register'
            defaults:
                _api_receive: false
            schemes: ['https']
            controller: App\Action\User\CreateMemberAction
        post_by_token:
            method: 'POST'
            path: '/user_temp.{_format}'
            requirements:
                _format: 'json\jsonld\html'
            defaults:
                _api_receive: false
                _format: 'json'
            schemes: ['https']
            security: "is_granted('IS_AUTHENTICATED_ANONYMOUSLY')"
            controller: App\Action\User\GetUserTempAction
    itemOperations:
        get: ~            
        delete:
            method: 'DELETE'
            path: '/user_temp/{token}'
            requirements:
                id: '\d+'
            security: 'is_granted("ROLE_ADMIN") and is_granted("IS_AUTHENTICATED_REMEMBERED")'
            security_message: 'Only administrators can access this resource'
            schemes: ['https']
