/**
 * Author: iracanyes
 * Date: 24/06/19
 * Description: Font Awesome library of icons used by the App
 */
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faCcAmex,
  faCcMastercard,
  faCcStripe,
  faCcPaypal,
  faCcVisa
} from '@fortawesome/free-brands-svg-icons';
import {
  faCheckCircle,
  faComments,
  faHeart,
  faUser,
  faSearch,
  faShoppingCart,
  faSignInAlt,
  faUserAlt,
  faUserCheck,
  faUserEdit,
  faUserCog,
  faSignOutAlt,
  faStar as faStarChecked,
  faStarHalfAlt,
  faStar,
  faBars,
  faAngleDoubleRight,
  faPlus,
  faShareAlt,
  faHandshake,
  faPaperPlane,
  faExclamationTriangle,
  faThumbsUp,
  faGrinWink,
  faInfoCircle,
  faUserCircle,
  faUserShield,
  faUserLock,
  faUsersCog,
  faHouseUser,
  faIdCard,
  faBoxes,
  faDollyFlatbed,
  faTruckLoading,
  faCartPlus,
  faShippingFast,
  faShip,
  faDollarSign,
  faCommentsDollar,
  faHandHoldingUsd,
  faShoppingBasket,
  faMapMarkerAlt,
  faMoneyCheckAlt,
  faInbox,
  faTruck,
  faHome,
  faEdit,
} from "@fortawesome/free-solid-svg-icons";

import {
  faStar as faStarEmpty
} from "@fortawesome/free-regular-svg-icons";

library.add([
  faAngleDoubleRight,
  faBars,
  faBoxes,
  faCartPlus,
  faCheckCircle,
  faComments,
  faCommentsDollar,
  faDollarSign,
  faDollyFlatbed,
  faEdit,
  faExclamationTriangle,
  faGrinWink,
  faHandHoldingUsd,
  faHandshake,
  faHeart,
  faHome,
  faHouseUser,
  faIdCard,
  faInfoCircle,
  faInbox,
  faMapMarkerAlt,
  faMoneyCheckAlt,
  faPaperPlane,
  faPlus,
  faSearch,
  faShareAlt,
  faShip,
  faShippingFast,
  faShoppingBasket,
  faShoppingCart,
  faSignOutAlt,
  faSignInAlt,
  faStar,
  faStarChecked,
  faStarEmpty,
  faStarHalfAlt,
  faThumbsUp,
  faTruck,
  faTruckLoading,
  faUser,
  faUserAlt,
  faUserCheck,
  faUserCircle,
  faUserCog,
  faUserEdit,
  faUserLock,
  faUserShield,
  faUsersCog,

]);
